### ISSUE TITLE
Refactor Person Class

### ISSUE THREAD

**Issue by C-likethis123** [AY1920S1-CS2103T-T13-1/main#43]
User story: As a user, I can add a new patient/donor/doctor. 

Progress: 
- [x] Add Patient
- [x] Add Age (Issue: #44)
- [x] Add Organ (Issue: #45 ) 
- [x] Add BloodType (Issue: #48)
- [x] Add Priority (Issue: #55)
- [x] Add Tissue Type (Issue: #47)
- [x] Add Donor (Issue: #51)
- [x] Add Age (Issue: #59)
- [x] Add Organ (Issue: #53)
- [x] Add BloodType (Issue: #54)
- [x] Add Tissue Type (Issue: #58)
- [x] Add expiry date (Issue: #50)
- [x] Add Doctor (Issue: #60)

**Comment by C-likethis123** [comment]
For some reason, this issue did not close even after merging all the related PRs.
